const techNames = {
    'nodejs': 'nodejs-original',
    'redis': 'redis-original',
    'firebase': 'firebase-plain',
    'flutter': 'flutter-original',
    'react': 'react-original',
    'express': 'express-original',
    'python': 'python-original',
    'jupyter': 'jupyter-original',
    'android': 'android-plain',
    'angularjs': 'angularjs-plain',
    'html5': 'html5-plain',
    'heroku': 'heroku-original',
    'jest': 'jest-plain',
    'javascript': 'javascript-plain',
    'mysql': 'mysql-original',
    'mongodb': 'mongodb-original',
    'nextjs': 'nextjs-original',
    'php': 'php-original',
    'postgresql': 'postgresql-original',
    'raspberrypi': 'raspberrypi-original',
    'rails': 'rails-plain',
    'ruby': 'ruby-plain',
    'tensorflow': 'tensorflow-original',
    'ubuntu': 'ubuntu-plain',
    'vscode': 'vscode-original',
    'unity': 'unity-original',
    'vuejs': 'vuejs-original',
    'vim': 'vim-original',
    'typeScript': 'typescript-original',
    'google-cloud-platform': 'googlecloud-original',
    'aws': 'aws-plain',
    'c': 'c-plain',
    'amazonwebservices': 'amazonwebservices-original',
    'dart': 'dart-original',

}
export default techNames;